### ISSUE TITLE
HTML/CSS

### ISSUE THREAD

**Issue by TimofeiShpak** [ilyachever/DigitalStudy#1]
https://github.com/ilyachever/DigitalStudy/blob/bc5e19b252eda3c1b5cd3aae3fa783ed69e83981/components/EmptyPage/index.html#L23

для изменения внешнего вида в БЭМ используется модификатор, поэтому правильнее будет переписать так btn_primary
просьба переписать это во всех файлах для всех классов

**Comment by TimofeiShpak** [comment]
https://github.com/ilyachever/DigitalStudy/blob/bc5e19b252eda3c1b5cd3aae3fa783ed69e83981/components/TaskItem/index.html#L24

task__user-logo - лишний, 
просто так не нужно писать класс, если он нигде больше не используется,
например: в качестве названия элемента, так как в названии элемента должно быть название блока или в других файлах css, js

**Comment by ilyachever** [comment]
> https://github.com/ilyachever/DigitalStudy/blob/bc5e19b252eda3c1b5cd3aae3fa783ed69e83981/components/TaskItem/index.html#L24
> 
> task__user-logo - лишний, просто так не нужно писать класс, если он нигде больше не используется, класс добавляют если его используют в качестве названия элемента, так как в названии элемента должно быть название блока или в других файлах css, js
> 
> тоже самое касается других классов, просьба перепроверить во всех файлах

При наведении на логотип появляется плашка "Исполнитель: Баранов В.В.". Для того, чтобы идентифицировать элемент, при наведении на который, эта плпшка будет всплывать не нужен доп. класс "task__user-logo"?

**Comment by TimofeiShpak** [comment]
> > https://github.com/ilyachever/DigitalStudy/blob/bc5e19b252eda3c1b5cd3aae3fa783ed69e83981/components/TaskItem/index.html#L24
> > 
> > task__user-logo - лишний, просто так не нужно писать класс, если он нигде больше не используется, класс добавляют если его используют в качестве названия элемента, так как в названии элемента должно быть название блока или в других файлах css, js
> > тоже самое касается других классов, просьба перепроверить во всех файлах
> 
> При наведении на логотип появляется плашка: "Исполнитель: Баранов В.В.". Для того, чтобы идентифицировать элемент, при наведении на который, эта плашка будет всплывать, не нужен доп. класс "task__user-logo"?

Сейчас при наведении на логотип появляется плашка? у меня не отображается
